(function () {
  'use strict';
  const samples = [{"id": "OLJCESPC7Z", "title": "Used Calculus Textbook", "description": "Gently used calculus textbook with light notes in the margins. Ideal for first-year math courses.", "price_cents": 3299, "metadata": {"image": "/static/img/products/campusloop/used-calculus-textbook.png"}, "seller_id": "campusloop-demo-seller"}, {"id": "66VCHSJNUP", "title": "Campus Club Hoodie", "description": "Pre-owned university hoodie in good condition. Cozy for late library nights and campus events.", "price_cents": 2499, "metadata": {"image": "/static/img/products/campusloop/campus-club-hoodie.png"}, "seller_id": "campusloop-demo-seller"}, {"id": "1YMWWN1N4O", "title": "Used 24-inch Study Monitor", "description": "Second-hand 24-inch monitor for dorm desks, coding projects, and remote classes.", "price_cents": 8599, "metadata": {"image": "/static/img/products/campusloop/study-desk-monitor.png"}, "seller_id": "campusloop-demo-seller"}, {"id": "L9ECAV7KIM", "title": "Commuter Bike", "description": "Reliable used bike for getting across campus quickly. Includes a basic lock and bell.", "price_cents": 12099, "metadata": {"image": "/static/img/products/campusloop/commuter-bike.png"}, "seller_id": "campusloop-demo-seller"}, {"id": "2ZYFJ3GM2N", "title": "Mini Dorm Fan", "description": "Compact fan for dorm rooms and study corners. Works well and fits on a small desk.", "price_cents": 1499, "metadata": {"image": "/static/img/products/campusloop/mini-dorm-fan.png"}, "seller_id": "campusloop-demo-seller"}, {"id": "0PUK6V6EV0", "title": "Adjustable Desk Lamp", "description": "Used LED desk lamp with adjustable brightness, perfect for evening study sessions.", "price_cents": 1699, "metadata": {"image": "/static/img/products/campusloop/adjustable-desk-lamp.png"}, "seller_id": "campusloop-demo-seller"}, {"id": "LS4PSXUNUM", "title": "Mechanical Keyboard", "description": "Pre-owned compact keyboard for programming, note-taking, and late-night assignments.", "price_cents": 3949, "metadata": {"image": "/static/img/products/campusloop/mechanical-keyboard.png"}, "seller_id": "campusloop-demo-seller"}, {"id": "9SIQT8TOJO", "title": "Reusable Water Bottle", "description": "Clean second-hand insulated bottle for classes, gym sessions, and long study days.", "price_cents": 949, "metadata": {"image": "/static/img/products/campusloop/reusable-water-bottle.png"}, "seller_id": "campusloop-demo-seller"}, {"id": "6E92ZMYYFZ", "title": "Intro CS Notes Bundle", "description": "Printed notes and practice sheets from an intro computer science course.", "price_cents": 1299, "metadata": {"image": "/static/img/products/campusloop/intro-cs-notes-bundle.png"}, "seller_id": "campusloop-demo-seller"}];
  const id = decodeURIComponent(location.pathname.split('/').filter(Boolean).pop());
  let listings = [];
  try { listings = JSON.parse(sessionStorage.getItem('campusloop-listing-preview')) || []; } catch (_) {}
  const item = listings.find(item => item.id === id) || samples.find(item => item.id === id);
  if (!item) return;
  document.getElementById('preview-title').textContent = item.title;
  document.getElementById('preview-price').textContent = '$' + (item.price_cents / 100).toFixed(2);
  document.getElementById('preview-description').textContent = item.description;
  document.getElementById('preview-label').textContent = item.seller_id === 'campusloop-demo-seller' ? 'Sample item.' : 'Previously viewed details. Availability will be checked before reservation.';
  const image = document.getElementById('preview-image');
  image.src = /^\/(static\/|api\/marketplace\/listings\/)/.test(item.metadata?.image || '') ? item.metadata.image : '/static/icons/listing-no-photo.svg';
  image.alt = item.title; image.hidden = false;
}());
